### ISSUE TITLE
Module not working on MIUI 14 A12

### ISSUE THREAD

**Issue by cakircan-cakir** [zgfg/SystemlessDebloater#3]
I installed the module on my Android 12 based MIUI 14 installed Xiaomi device and edited the config file to remove GetApps and MiBrowser.  When I restarted the phone, I still saw that the apps were not deleted.

> **Magisk Screenshot**

![Screenshot_2023-07-05-10-05-27-529_com topjohnwu magisk](https://github.com/zgfg/SystemlessDebloater/assets/57761847/cf8f2a3c-67ee-4ff6-a59a-35bb44038945)

> **Config Screenshot**

![Screenshot_2023-07-05-10-07-10-762_com mixplorer](https://github.com/zgfg/SystemlessDebloater/assets/57761847/1e3fd7e4-5c37-4a1d-a8fb-b3c57cdc8ee0)

[Last Module Log](https://hastebin.com/share/qoyilequri.bash)

Device: Xiaomi 10T
Rom: MIUI 14 CN

**Comment by zgfg** [comment]
Inspect Internal memory, Download folder and remove the old SystemlessDebloaterList.sh (if you have it)

Keep there only the new
SystemlessDebloater.cfg

In the cfg you don't put (please read Readme here and follow the links to Wiki and XDA for further instructions)
com.xiaomi.... 

but only the final names like 

MiuiSuperMarket
MiBrowser

(I cannot properly search since your log file does not download but in browser I didn't see any app with the name like GetApps)

Then reinstall module and reboot

And please, if you want to get help then don't attach screenshots (as you did for the cfg file), but attach both cfg and log file that when I click on (test yourself), that it will download me the files to my mob, that I can open them locally  in the editor, search, copy/paste, etc (your log file does not download but instead opens in the browser that is not useful for searching through its hundreds of lines)

From the log, it says at the beginning

Final DebloatList=""

Hence it seems it didn't find cfg file in Download folder at the time when you were installing the module or you had the old SystemlessDebloaterList.sh with the old DebloatList there

**Comment by zgfg** [comment]
Hence, module does work on MIUI 14 (I have it) but it must be properly used

Whenever you change the cfg file, you must reinstall the module and reboot (as it says in the instructions)

Module reads cfg file only when being (re)installed - once you install and debloat the apps you wanted, you can move out cfg file - it will not be used until the next reinstallation or update of the module

And module performs debloating only when being rebooted (that's how Magisk modules work)

(To support updating for users who are switching from sh input file to cfg input file, the old sh file has precedence (hence if sh file is present [and empty or not], module will ignore the cfg file) - to properly use/read/process the new cfg file, remove the old sh file and reinstall the module and reboot the phone

**Comment by zgfg** [comment]
When you properly configure the module (change cfg file, reinstall the module and reboot) you must find in your log:

Input config file: /storage/emulated/0/Download/SystemlessDebloater.cfg

Proving that cfg file was present and that module found and read the cfg file, and then like (apps I debloat, as in my cfg file) - not empty list as in your log 

Input DebloatList="
CatchLog
CneApp
EasterEgg
Email
GoogleFeedback
GooglePartnerSetup
Joyose
MiBrowserGlobal
MiGameService
MiLinkService
MiMover
MiService
MiShare
MiuiBugReport
PaymentService
Stk
TouchAssistant
Traceur
XiaomiSimActivateService
ims
"

**Comment by zgfg** [comment]
No issue - module does work on MIUI 14.
Answered to user how to properly set a module but no feedback for over a week

**Comment by cakircan-cakir** [comment]
Thank you very much for your detailed answer.  When I updated the config file, I didn't know that I had to reload the module.  I edited the config file according to the instructions and when I reinstalled the module, the applications seem to be disabled, although not completely deleted.  They still have icons in the launcher, but they do not open when clicked.  We were also told that we should write the name of the application in the config file, but this is not correct.  It is necessary to write the folder in which the application is in the system directory.  For example, the GetApps application is located in the MiuiSuperMarket folder under system/app.  Instead of writing GetApps in the config file, it is necessary to write MiuiSuperMarket.  Finally, why couldn't it completely delete the found icons in the launcher?

![Screenshot_2023-07-16-18-40-42-057_com miui home](https://github.com/zgfg/SystemlessDebloater/assets/57761847/7f143574-07bb-416b-b920-a5d931475656)

![Screenshot_2023-07-16-18-52-41-716_com miui securitycenter](https://github.com/zgfg/SystemlessDebloater/assets/57761847/d8499243-5550-4261-beb6-d62975bd7601)

![Screenshot_2023-07-16-18-53-27-876_com miui securitycenter](https://github.com/zgfg/SystemlessDebloater/assets/57761847/2bad4856-95b4-4be5-a187-c29c79c97076)


[Logs And Config](https://cdn.discordapp.com/attachments/1124345084779974707/1130162752560836679/Logs_and_Config.zip)

**Comment by zgfg** [comment]
App name in the instructions refers to the <name> from the <name>.apk

Eg, 
MiBrowserGlobal

will debloat (path on my MIUI):
/product/priv-app/MiBrowserGlobal/MiBrowserGlobal.apk

Hence, MiBrowserGlobal is both the folder name and the (file) name part of the MiBrowserGlobala.pk

However, it is not Browser or something that will show on the Home screen
