### ISSUE TITLE
Magisk Alpha - No CFG Created or Read and No Log

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [zgfg/SystemlessDebloater#5]
I noticed this module stopped reading my config file a few days ago so I tried re-installing the module, but after changing the name of the original config I noticed that the module no longer actually creates the config files in the download folder anymore (even though it says it does in the Magisk log). This of course also means that it's not reading it either. I'm using Magisk Alpha as of last night, but the issue appears to have happened a number of days ago judging by the modified dates.

Edit: I tried placing the cfg manually from the zip and editing it just to see. Upon re-installing the module, it didn't even see it and proceeded to "create a new one." When I looked in the folder it hadn't created a new one, and the one I created was still there unedited. Upon rebooting, no log file was created.

**Comment by zgfg** [comment]
Which module version are you using?

Compared to XDA, seems you're using latest Magisk Alpha

Latest Aloha has changed the path to access Internal memory and the module's customize.sh script does no more access cfg file

Since developers of Alpha constantly change something - without  documentation (or commenting on ly in their TG channel in Chinese) and since Magisk Alpha is closed source, I have no plans to support the unofficial Magisk Aloha🤪

Module works fine with (latest) official Magisk Canary and Stable (and for me also on latest Magisk Delta)

**Comment by zgfg** [comment]
Unofficially (and module will not be upgraded for Magisk Alpha shenanigans) please test the attached v1.5.4a:
[SystemlessDebloater_v1.5.4a.zip](https://github.com/zgfg/SystemlessDebloater/files/13115059/SystemlessDebloater_v1.5.4a.zip)

**Comment by zgfg** [comment]
Nobody else commented or opened an issue for Alpha

Also, it works fine with Magisk v26400/26401 that shares the same mounting code that was implemented and released first in Alpha

Hence closing for now
